console_title_template = 'Exploring {{ .PWD }}'
version = 3
final_space = true

[palette]
  black = '#181926'
  blue = '#8aadf4'
  green = '#a6da95'
  orange = '#f5a97f'
  red = '#ed8796'
  sky = '#91d7e3'
  white = '#cad3f5'
  yellow = '#eed49f'

[transient_prompt]
  template = '{{.Code}}'
  foreground = 'yellow'
  background = 'transparent'
  newline = true

[maps]
  [maps.user_name]
    u0_a251 = 'pyapple'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = true
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ dateInZone "3:04 PM" .CurrentDate "Asia/Jakarta" }} '
    foreground = 'p:white'
    background = 'p:black'
    type = 'time'
    style = 'diamond'

  [[blocks.segments]]
    template = ' {{ if .SSHSession }} {{ end }}{{ .UserName }} '
    foreground = 'p:black'
    background = 'p:yellow'
    type = 'session'
    style = 'powerline'

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    template = '  {{  .Path  }} '
    foreground = 'p:black'
    powerline_symbol = ''
    background = 'p:blue'
    type = 'path'
    style = 'powerline'

    [blocks.segments.properties]
      style = 'unique'
		folder_separator_icon = '  '

  [[blocks.segments]]
    template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    foreground = 'p:black'
    powerline_symbol = ''
    background = 'p:green'
    type = 'git'
    style = 'powerline'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}', '{{ if gt .Ahead 0 }}p:white{{ end }}']
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}', '{{ if gt .Ahead 0 }}#49416D{{ end }}', '{{ if gt .Behind 0 }}#7A306C{{ end }}']

    [blocks.segments.properties]
      branch_template = '{{ trunc 25 .Branch }}'
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    template = '  '
    foreground = 'p:black'
    powerline_symbol = ''
    background = 'p:yellow'
    type = 'root'
    style = 'powerline'


[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

	[[blocks.segments]]
	type = 'text'
	style = 'plain'
	foreground = 'blue'
	template = ' ● '

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = '{{ if gt .Code 0 }} {{.Code}}{{ else }}{{ end }}'
    foreground = 'p:black'
    background = 'p:green'
    type = 'status'
    style = 'diamond'
    background_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']

    [blocks.segments.properties]
      always_enabled = false
